### ISSUE TITLE
The avr-size.exe is not suit for avr mcu

### ISSUE THREAD

**Issue by wanggaoteng** [ZakKemble/avr-gcc-build#3]
I download the .zip file below:
![image](https://user-images.githubusercontent.com/29191854/213910249-825f2108-24dd-445d-9a4a-8e78ad852d92.png)
and unzip it, the path of avr-size.exe is:
avr-gcc-12.1.0-x64-windows\bin
look at the help of avr-size.exe:
![image](https://user-images.githubusercontent.com/29191854/213910368-90e9a6fa-7ba7-41e8-9e14-1283efa196ed.png)
It lacks the --mcu and --mlist-devices as the following picture shows:
![image](https://user-images.githubusercontent.com/29191854/213910485-f5a2c025-9505-44bd-ba66-db86d2f7a281.png)

**Comment by ZakKemble** [comment]
avr-size does not need to know the MCU to show you the memory usage (omit the --mcu arg). If you want to get the usage as a percentage then the new correct way is to use `avr-objdump` with the `-Pmem-usage` argument: `avr-objdump -Pmem-usage myproject.elf` which will output something like:

```
myproject.elf:     file format elf32-avr
AVR Memory Usage
----------------
Device: attiny402

Program:    1934 bytes (47.2% Full)
(.text + .data + .bootloader)

Data:         16 bytes (6.2% Full)
(.data + .bss + .noinit)
```

This is because the MCU and available memory sizes are now embedded into the .elf file. See here - http://web.archive.org/web/20211026214736/https://www.avrfreaks.net/forum/where-does-avr-size-get-data-supported-devices

**Comment by wanggaoteng** [comment]
> avr-size does not need to know the MCU to show you the memory usage (omit the --mcu arg). If you want to get the usage as a percentage then the new correct way is to use `avr-objdump` with the `-Pmem-usage` argument: `avr-objdump -Pmem-usage myproject.elf` which will output something like:
> 
> ```
> myproject.elf:     file format elf32-avr
> AVR Memory Usage
> ----------------
> Device: attiny402
> 
> Program:    1934 bytes (47.2% Full)
> (.text + .data + .bootloader)
> 
> Data:         16 bytes (6.2% Full)
> (.data + .bss + .noinit)
> ```
> 
> This is because the MCU and available memory sizes are now embedded into the .elf file. See here - https://web.archive.org/web/20211026214736/https://www.avrfreaks.net/forum/where-does-avr-size-get-data-supported-devices

I see, thank you for reply.
Best regards.

**Comment by atoomnetmarc** [comment]
Thanks!

I used your help to write a post-build event for Microchip Studio to get Memory Usage back: `$(ToolchainDir)/avr-objdump -Pmem-usage "$(OutputDirectory)/$(OutputFileName)$(OutputFileExtension)"`
